require("config.lazy")

-- <my_options>

vim.opt.number = true
vim.opt.relativenumber = true
-- set expandtab
vim.opt.expandtab = true
-- set shiftwidth=2
vim.opt.shiftwidth = 2
-- set tabstop=2
vim.opt.tabstop = 2

vim.opt.colorcolumn = "80"
vim.opt.cursorline = true

vim.o.signcolumn = "auto"

-- -- always show tabline
-- vim.o.showtabline = 2

-- Enable the autoread option to automatically read the file if changes are detected externally
vim.opt.autoread = true
-- Create an autocommand group for automatic reloading
-- Generated by Gemini https://share.google/aimode/xonpysszGMvCPrwrM
-- vim.api.nvim_create_autocmd({"BufEnter", "CursorHold", "CursorHoldI", "FocusGained"}, {
--   group = vim.api.nvim_create_augroup("CheckTimeGroup", { clear = true }),
--   callback = function()
--     -- Only run checktime if not in the command-line window
--     if vim.fn.mode() ~= 'c' then
--       vim.cmd("checktime")
--     end
--   end,
--   pattern = {"*"}, -- Apply to all file types
-- })

-- </my_options>

vim.cmd("colorscheme kanagawa")

-- From nvim-tree-sitter docs:
-- https://github.com/nvim-treesitter/nvim-treesitter?tab=readme-ov-file#folding
vim.opt.foldmethod = "expr"
vim.opt.foldexpr = "v:lua.vim.treesitter.foldexpr()"
vim.opt.foldlevelstart = 99
-- vim.opt.foldmethod = "indent"

vim.keymap.set("n", "<leader>rw", ":%s/<c-r><c-w>/", {})
vim.keymap.set("n", "<space>rw", ":%s/<c-r><c-w>/", {})
vim.keymap.set("n", "<leader>ry", ':%s/<c-r>"/', {})
vim.keymap.set("n", "<space>ry", ':%s/<c-r>"/', {})

vim.keymap.set("n", "<leader>rs", ":%s/", {})
vim.keymap.set("n", "<space>rs", ":%s/", {})

vim.keymap.set("n", "<leader>ra", ":cfdo %s/<c-r><c-w>/", {})
vim.keymap.set("n", "<space>ra", ":cfdo %s/<c-r><c-w>/", {})

vim.keymap.set("n", "s", ":update<cr>", {})

-- Window navigation and manipulation
vim.keymap.set("n", "go", "<C-w><C-o>", { desc = "Close other windows (but keep focussed open)" })
vim.keymap.set("n", "gh", "<C-w>h", { desc = "Go to window left" })
vim.keymap.set("n", "<C-h>", "<C-w>h", { desc = "Go to window left" })
-- <C-h> interferes with fzf-lua's keybindings so I'm removing it, but I'm trying it again:
-- vim.keymap.set("t", "<C-h>", "<C-\\><C-n><C-w>h", { desc = "Go to window left whilst in terminal" })
vim.keymap.set("t", "<C-w>h", "<C-\\><C-n><C-w>h", { desc = "Jump to window to the left of terminal" })
vim.keymap.set("n", "gH", "<C-w>H", { desc = "Move window left" })

vim.keymap.set("n", "gl", "<C-w>l", { desc = "Go to window right" })
vim.keymap.set("n", "<C-l>", "<C-w>l", { desc = "Go to window right" })
-- <C-l> interferes with fzf-lua's keybindings so I'm removing it, but I'm trying it again:
-- vim.keymap.set("t", "<C-w>l", "<C-\\><C-n><C-w>l", { desc = "Just to window to the right of terminal window" })

vim.keymap.set("n", "gL", "<C-w>L", { desc = "Move window right" })
vim.keymap.set("n", "gk", "<C-w>k", { desc = "Go to window up" })
vim.keymap.set("n", "gj", "<C-w>j", { desc = "Go to window down" })

vim.keymap.set("n", "g-", "<C-w>c", { desc = "Close current window" })

vim.keymap.set("n", "g=", "<C-w>v<C-w>l", { desc = "Vertically split current window (same buffer) and jump to it" })
vim.keymap.set("n", "gv", "<C-w>v<C-w>l", { desc = "Vertically split current window (same buffer) and jump to it" })
vim.keymap.set("n", "gs", "<C-w>s<C-w>j", { desc = "Vertically split current window (same buffer) and jump to it" })

vim.keymap.set("n", "gw", "<C-w>w", { desc = "Cycle forward window/popup" })
vim.keymap.set("n", "gW", "<C-w>W", { desc = "Jump to window/popup" })
vim.keymap.set("n", "gT", "<C-w>T", { desc = "Move window to new tab" })
vim.keymap.set("n", "gt", "<C-w>t", { desc = "Go to top window" })
vim.keymap.set("n", "gb", "<C-w>b", { desc = "Go to bottom window" }) -- Often same as <C-w><C-o> but depends on context

---
-- Tab navigation and manipulation
vim.keymap.set("n", "t=", ":tabnew<CR>", { desc = "Create new tab" })
vim.keymap.set("n", "t-", ":tabclose<CR>", { desc = "Create new tab" })
vim.keymap.set("n", "th", ":tabprevious<CR>", { desc = "Go to previous tab" })
vim.keymap.set("n", "tl", ":tabnext<CR>", { desc = "Go to next tab" })
vim.keymap.set("n", "t<", ":-tabmove<CR>", { desc = "Move tab left" })
vim.keymap.set("n", "t>", ":+tabmove<CR>", { desc = "Move tab right" })
vim.keymap.set("n", "t0", ":tabfirst<CR>", { desc = "Jump to first tab" })
vim.keymap.set("n", "t9", ":tablast<CR>", { desc = "Jump to last tab" })

-- <search_related_maps>
vim.opt.ignorecase = true -- Search is case-insensitive by default
vim.opt.smartcase = true -- If search contains uppercase, become case-sensitive

vim.keymap.set("n", "<Bslash>n", ":nohlsearch<CR>", { desc = "Clear search highlight" })
-- </search_related_maps>

vim.keymap.set("n", "gr", ":checktime<CR>", { desc = "Reload file if changed externally" })

-- <custom_ex_commands>

-- Port these commands:
-- :command DiffThis windo diffthis
-- :command DiffOff windo diffoff

-- <diff-commands>
--
-- NOTE, see ./lua/plugins/git_plugins.lua for more diff related commands like
-- :DiffBuffer

--
vim.api.nvim_create_user_command("DiffWindows", function()
	vim.cmd("windo diffthis")
end, {})

vim.api.nvim_create_user_command("DiffOff", function()
	vim.cmd("windo diffoff")
end, {})
-- <diff-commands>

vim.api.nvim_create_user_command("YankVimPathLineNum", function()
	local relative_path = vim.fn.fnamemodify(vim.fn.expand("%"), ":~:.")
	local line_number = vim.fn.line(".")
	local path_line_num = relative_path .. ":" .. line_number
	vim.fn.setreg("+", path_line_num)
	vim.fn.setreg('"', path_line_num)
	vim.print("Copied '" .. path_line_num .. "' to clipboard")
end, {})

vim.api.nvim_create_user_command("YankRefToFilePath", function()
	local relative_path = vim.fn.fnamemodify(vim.fn.expand("%"), ":~:.")
	local line_number = vim.fn.line(".")
	local file_ref = "@" .. relative_path
	vim.fn.setreg("+", file_ref)
	vim.fn.setreg('"', file_ref)
	vim.print("Copied '" .. file_ref .. "' to clipboard")
end, {})

vim.keymap.set(
	"n",
	"<space>yrf",
	":YankRefToFilePath<CR>",
	{ desc = "[Y]ank Claude-friendly [r]eference to [f]ile path" }
)

vim.api.nvim_create_user_command("YankRefToFileLineNum", function(opts)
	local relative_path = vim.fn.fnamemodify(vim.fn.expand("%"), ":~:.")
	local path_line_ref
	if opts.range == 0 then
		-- No range provided, use current line
		local line_number = vim.fn.line(".")
		path_line_ref = "@" .. relative_path .. "#L" .. line_number
	elseif opts.line1 == opts.line2 then
		-- Single line selected
		path_line_ref = "@" .. relative_path .. "#L" .. opts.line1
	else
		-- Range selected
		path_line_ref = "@" .. relative_path .. "#L" .. opts.line1 .. "-" .. opts.line2
	end
	vim.fn.setreg("+", path_line_ref)
	vim.fn.setreg('"', path_line_ref)
	vim.print("Copied '" .. path_line_ref .. "' to clipboard")
end, { range = true })

vim.keymap.set(
	"n",
	"<space>yrl",
	"<Cmd>YankRefToFileLineNum<CR>",
	{ desc = "Yank agent-friendly file and line number reference" }
)
vim.keymap.set(
	"v",
	"<space>yrl",
	":YankRefToFileLineNum<CR>",
	{ desc = "Yank agent-friendly file and line range reference" }
)

vim.api.nvim_create_user_command("YankPath", function()
	local relative_path = vim.fn.fnamemodify(vim.fn.expand("%"), ":~:.")
	vim.fn.setreg("+", relative_path)
	vim.fn.setreg('"', relative_path)
	vim.print("Copied '" .. relative_path .. "' to clipboard")
end, {})

vim.keymap.set("n", "<space>yfp", ":YankPath<CR>", { desc = "[Y]ank [f]ile's [p]ath to file (relative to $CWD)" })

vim.api.nvim_create_user_command("YankFilename", function()
	local filename = vim.fn.expand("%:t")
	vim.fn.setreg("+", filename)
	vim.fn.setreg('"', filename)
	vim.print("Copied '" .. filename .. "' to clipboard")
end, {})

vim.keymap.set("n", "<space>yfn", ":YankFilename<CR>", { desc = "[Y]ank [f]ilename" })

vim.api.nvim_create_user_command("YankAbsolutePath", function()
	local absolute_path = vim.fn.fnamemodify(vim.fn.expand("%"), ":p")
	vim.fn.setreg("+", absolute_path)
	vim.fn.setreg('"', absolute_path)
	vim.print("Copied '" .. absolute_path .. "' to clipboard")
end, {})
vim.keymap.set("n", "<space>yfa", ":YankAbsolutePath<CR>", { desc = "[Y]ank [f]ile's [a]bsolute path" })

vim.api.nvim_create_user_command("CommentJSConsoleCalls", function()
	-- vim.cmd("%s/^\([:space:]*\\)console/\1\\/\\/ console/ga")
	vim.cmd("%s/^\\([[:space:]]*\\)console/\\1\\/\\/ console/gc")
end, {})

vim.api.nvim_create_user_command("UncommentJSConsoleCalls", function()
	-- vim.cmd("%s/^\([[:space:]]*\\)console/\1\\/\\/ console/ga")
	vim.cmd("%s/^\\([[:space:]]*\\)\\/\\/[[:space:]]\\?console/\\1console/gc")
end, {})

vim.api.nvim_create_user_command("CommentHTML", function()
	vim.cmd("TCommentAs html")
	-- vim.cmd
end, {})

vim.api.nvim_create_user_command("ToggleTodo", function()
	local word = vim.fn.expand("<cword>")
	if word == "TODO" then
		vim.cmd('normal! "_ciwDONE')
		vim.cmd("normal! b") -- I added this to move the cursor back after replacement
	elseif word == "DONE" then
		vim.cmd('normal! "_ciwTODO')
		vim.cmd("normal! b")
	end
end, {})

vim.keymap.set("n", "tt", ":ToggleTodo<CR>", { desc = "Toggle TODO/DONE" })

-- vim.api.nvim_create_user_command("Format", function(args)
-- 	local range = nil
-- 	if args.count ~= -1 then
-- 		local end_line = vim.api.nvim_buf_get_lines(0, args.line2 - 1, args.line2, true)[1]
-- 		range = {
-- 			start = { args.line1, 0 },
-- 			["end"] = { args.line2, end_line:len() },
-- 		}
-- 	end
-- 	require("conform").format({ async = true, lsp_format = "fallback", range = range })
-- end, { range = true })

-- This is used to show LSP diagnostics on cursorhold:
vim.api.nvim_create_autocmd({ "CursorHold" }, {
	pattern = "*",
	callback = function()
		vim.diagnostic.open_float({ scope = "cursor", focusable = true })
	end,
})
vim.opt.updatetime = 500 -- Trigger CursorHold after 500ms of inactivity

vim.api.nvim_create_user_command("InsertDate", function()
	local date = os.date("%Y-%m-%d")
	vim.api.nvim_put({ date }, "c", false, true)
end, {})

vim.keymap.set("n", "<space>id", ":InsertDate<CR>", { desc = "Insert current date (YYYY-MM-DD)" })

vim.api.nvim_create_user_command("InsertTime", function()
	local time = os.date("%H:%M")
	vim.api.nvim_put({ time }, "c", false, true)
end, {})

vim.keymap.set("n", "<space>it", ":InsertTime<CR>", { desc = "Insert current time (HH:MM)" })

-- </custom_ex_commands>

-- <markdown_keymaps>
vim.api.nvim_create_autocmd("FileType", {
	pattern = "markdown",
	callback = function(ev)
		vim.keymap.set("x", "_", [[c_<C-r>"_<Esc>]], {
			buffer = ev.buf,
			desc = "Wrap selection in markdown italics",
		})
		vim.keymap.set("x", "*", [[c**<C-r>"**<Esc>]], {
			buffer = ev.buf,
			desc = "Wrap selection in markdown bold",
		})
		vim.keymap.set("x", "`", [[c`<C-r>"`<Esc>]], {
			buffer = ev.buf,
			desc = "Wrap selection in markdown inline code",
		})

		vim.keymap.set("x", "~", [[c~~<C-r>"~~<Esc>]], {
			buffer = ev.buf,
			desc = "Wrap selection in markdown strikethrough",
		})
	end,
})

-- </markdown_keymaps>
